### ISSUE TITLE
TGEvent's Metadata String Field Cause Deserialization Exception

### ISSUE THREAD

**Issue by thorbenprimke** [tapglue/android_sdk#4]
If the metadata field actually includes a JSON object instead of a plain string, GSON cannot deserialize into a String. Should the field type be `JsonObject` or a `Map`? 

Exception:

```
01-06 10:42:16.635 27715-27715/com.femlite.app E/Tapglue: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 691 path $.events[1].metadata
01-06 10:42:16.635 27715-27715/com.femlite.app W/System.err: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 691 path $.events[1].metadata
01-06 10:42:16.635 27715-27715/com.femlite.app W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221)
01-06 10:42:16.635 27715-27715/com.femlite.app W/System.err:     at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
01-06 10:42:16.635 27715-27715/com.femlite.app W/System.err:     at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
01-06 10:42:16.635 27715-27715/com.femlite.app W/System.err:     at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
01-06 10:42:16.635 27715-27715/com.femlite.app W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:117)
01-06 10:42:16.635 27715-27715/com.femlite.app W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:217)
01-06 10:42:16.635 27715-27715/com.femlite.app W/System.err:     at com.google.gson.Gson.fromJson(Gson.java:861)
01-06 10:42:16.635 27715-27715/com.femlite.app W/System.err:     at com.google.gson.Gson.fromJson(Gson.java:826)
01-06 10:42:16.635 27715-27715/com.femlite.app W/System.err:     at retrofit.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:36)
01-06 10:42:16.635 27715-27715/com.femlite.app W/System.err:     at retrofit.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:24)
01-06 10:42:16.635 27715-27715/com.femlite.app W/System.err:     at retrofit.OkHttpCall.parseResponse(OkHttpCall.java:148)
01-06 10:42:16.635 27715-27715/com.femlite.app W/System.err:     at retrofit.OkHttpCall.access$100(OkHttpCall.java:29)
01-06 10:42:16.635 27715-27715/com.femlite.app W/System.err:     at retrofit.OkHttpCall$1.onResponse(OkHttpCall.java:94)
01-06 10:42:16.635 27715-27715/com.femlite.app W/System.err:     at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
01-06 10:42:16.635 27715-27715/com.femlite.app W/System.err:     at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
01-06 10:42:16.635 27715-27715/com.femlite.app W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
01-06 10:42:16.635 27715-27715/com.femlite.app W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
01-06 10:42:16.635 27715-27715/com.femlite.app W/System.err:     at java.lang.Thread.run(Thread.java:818)
01-06 10:42:16.635 27715-27715/com.femlite.app W/System.err: Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 691 path $.events[1].metadata
01-06 10:42:16.635 27715-27715/com.femlite.app W/System.err:     at com.google.gson.stream.JsonReader.nextString(JsonReader.java:838)
01-06 10:42:16.635 27715-27715/com.femlite.app W/System.err:     at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:422)
01-06 10:42:16.635 27715-27715/com.femlite.app W/System.err:     at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:410)
01-06 10:42:16.635 27715-27715/com.femlite.app W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:117)
01-06 10:42:16.635 27715-27715/com.femlite.app W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:217)
01-06 10:42:16.635 27715-27715/com.femlite.app W/System.err:    ... 17 more
```

**Comment by dlsniper** [comment]
@thorbenprimke do you have by any chance a small code sample that could help reproduce this faster? Thank you.

**Comment by dlsniper** [comment]
@thorbenprimke I've just noticed you've also sent: https://github.com/tapglue/android_sdk/pull/8
If you can please add a small code sample for this to have in mind for our tests then I'll merge it asap. Thank you.
